[default]
APP_NAME = "TodoList"
SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite3"
SQLALCHEMY_TRACK_MODIFICATIONS = false

[development]
ENV_NAME = "Dev"

[production]
ENV_NAME = "Production"

[homologation]
ENV_NAME = "Homologation"

[testing]
ENV_NAME = "Quality"


